application: xinforce23
version: 1
runtime: go
api_version: go1

handlers:
- url: /images
  static_dir: images
- url: /static
  static_dir: static
- url: /favicon.ico
  static_files: content/images/favicon.ico
  upload: content/images/favicon.ico
- url: /scripts
  static_dir: scripts
- url: /bower_components
  static_dir: bower_components
- url: /content
  static_dir: content
- url: /.*
  script: _go_app
- url: /(.*\.html)
  mime_type: text/html
  static_files: static/\1
  upload: static/(.*\.html)
- url: /_ah/spi/.*
  script: _go_app
