/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-11-17 18:43:33 UTC)
 * on 2015-01-05 at 04:45:47 UTC 
 * Modify at your own risk.
 */

package localhost.inforce.model;

/**
 * Model definition for UserInfo.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the inforce. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class UserInfo extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("Companies")
  private java.lang.String companies;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("Firstname")
  private java.lang.String firstname;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("Lastname")
  private java.lang.String lastname;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("TimeAdded")
  private com.google.api.client.util.DateTime timeAdded;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("Username")
  private java.lang.String username;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCompanies() {
    return companies;
  }

  /**
   * @param companies companies or {@code null} for none
   */
  public UserInfo setCompanies(java.lang.String companies) {
    this.companies = companies;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getFirstname() {
    return firstname;
  }

  /**
   * @param firstname firstname or {@code null} for none
   */
  public UserInfo setFirstname(java.lang.String firstname) {
    this.firstname = firstname;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getLastname() {
    return lastname;
  }

  /**
   * @param lastname lastname or {@code null} for none
   */
  public UserInfo setLastname(java.lang.String lastname) {
    this.lastname = lastname;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getTimeAdded() {
    return timeAdded;
  }

  /**
   * @param timeAdded timeAdded or {@code null} for none
   */
  public UserInfo setTimeAdded(com.google.api.client.util.DateTime timeAdded) {
    this.timeAdded = timeAdded;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getUsername() {
    return username;
  }

  /**
   * @param username username or {@code null} for none
   */
  public UserInfo setUsername(java.lang.String username) {
    this.username = username;
    return this;
  }

  @Override
  public UserInfo set(String fieldName, Object value) {
    return (UserInfo) super.set(fieldName, value);
  }

  @Override
  public UserInfo clone() {
    return (UserInfo) super.clone();
  }

}
